declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
  }
  export type Icon = FC<IconProps>;
  export const Accordion: Icon;
  export const AlertCircle: Icon;
  export const AlertTriangle: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const Award: Icon;
  export const BookOpen: Icon;
  export const Building2: Icon;
  export const Calendar: Icon;
  export const Check: Icon;
  export const CheckCircle: Icon;
  export const ChevronDown: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ChevronUp: Icon;
  export const Circle: Icon;
  export const Clock: Icon;
  export const CreditCard: Icon;
  export const ExternalLink: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const GraduationCap: Icon;
  export const GripVertical: Icon;
  export const Info: Icon;
  export const Library: Icon;
  export const Loader2: Icon;
  export const Lock: Icon;
  export const LogOut: Icon;
  export const Mail: Icon;
  export const Minus: Icon;
  export const Moon: Icon;
  export const MoreHorizontal: Icon;
  export const OctagonX: Icon;
  export const PanelLeft: Icon;
  export const Phone: Icon;
  export const Quote: Icon;
  export const Search: Icon;
  export const Shield: Icon;
  export const Smartphone: Icon;
  export const Sparkles: Icon;
  export const Star: Icon;
  export const Sun: Icon;
  export const Target: Icon;
  export const TrendingUp: Icon;
  export const User: Icon;
  export const Users: Icon;
  export const Wallet: Icon;
  export const X: Icon;
  export const XCircle: Icon;
}
